// Copies the router ABI out of the Foundry artifact (../out) into src/abi.ts so the package needs no forge at
// install time. Run after `forge build`; CI fails if the committed file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = resolve(here, "../../out/NoirpayRouter.sol/NoirpayRouter.json");
const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
const out = `// Generated by scripts/gen-abi.mjs from out/NoirpayRouter.sol/NoirpayRouter.json — do not edit by hand.\nexport const NoirpayRouterAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;
writeFileSync(resolve(here, "../src/abi.ts"), out);
console.log(`src/abi.ts: ${abi.length} items`);
