// Copies the router ABI out of the Foundry artifact (../out) into src/abi.ts so the package needs no forge at
// install time. Run after `forge build`; CI fails if the committed file is stale.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = resolve(here, "../../out/NoirpayRouter.sol/NoirpayRouter.json");
const { abi, deployedBytecode } = JSON.parse(readFileSync(artifact, "utf8"));
// Runtime code without the trailing CBOR metadata (its last 2 bytes are its length), so any build of the same source
// with the same compiler settings hashes the same, whatever its file paths.
const code = Buffer.from(deployedBytecode.object.slice(2), "hex");
const stripped = code.subarray(0, code.length - (code.readUInt16BE(code.length - 2) + 2));
// `cast` comes with Foundry, which this script already needs for ../out; keeps the script dependency-free.
const codeHash = execFileSync("cast", ["keccak", "0x" + stripped.toString("hex")]).toString().trim();
const out = `// Generated by scripts/gen-abi.mjs from out/NoirpayRouter.sol/NoirpayRouter.json — do not edit by hand.\nexport const NoirpayRouterAbi = ${JSON.stringify(abi, null, 2)} as const;\n\n/** keccak256 of the router's runtime code with the CBOR metadata stripped (see verifyDeployment). */\nexport const ROUTER_CODE_HASH = ${JSON.stringify(codeHash)} as const;\n`;
writeFileSync(resolve(here, "../src/abi.ts"), out);
console.log(`src/abi.ts: ${abi.length} items, code hash ${codeHash}`);
